/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class RandomQuoteTest {
    @Test public void testCanGetQuote() {
        Quote quote = RandomQuote.FindQuote();
        System.out.println(quote.toString());
        assertNotNull(quote);
        assertNotNull(quote.getAuthor());
        assertNotNull(quote.getText());
    }
}
